---
- name: get AiiDA MaX examples
  git:
    repo: https://github.com/aiidateam/aiida-max-examples.git
    dest: "{{ aiida_examples_folder }}/aiida-max-examples"
    version: master

- name: get AiiDA demos
  git:
    repo: https://github.com/aiidateam/aiida_demos.git
    dest: "{{ aiida_examples_folder }}/aiida-demos"
    version: master

- name: make sure the solutions file is not there
  file:
    path: "{{ aiida_examples_folder }}/aiida-demos/tutorial/solution.ipynb"
    state: "absent"

- name: create the compiled versions of the querybuilder tutorial (only tutorial, no solutions)
  make:
    chdir: "{{ aiida_examples_folder }}/aiida-demos/tutorial"
    target: "tutorial.ipynb"
